# Generated by Django 5.1.7 on 2025-03-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_patient_date_of_birth_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='consultation_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
